var band_data = {
  "Colindale_AA": {
    "Workplace": "Colindale",
    "Geography": "Inner",
    "Grade": "AA",
    "Minimum": 23469,
    "Maximum": 23469,
    "AfC region": "Colindale - High Cost Area Supplement (outer)",
    "AfC band": "Band 3",
    "Entry step point": 25838,
    "Intermediate step point": "-",
    "Top step point": 27285,
    "Years until pay progression": 2,
    "Difference in entry pay": -2369,
    "Difference after 2 years": -3816,
    "Difference after 3 years": -3816,
    "Difference after 5 years": -3816
  },
  "Colindale_AO": {
    "Workplace": "Colindale",
    "Geography": "Inner",
    "Grade": "AO",
    "Minimum": 24489,
    "Maximum": 25066,
    "AfC region": "Colindale - High Cost Area Supplement (outer)",
    "AfC band": "Band 4",
    "Entry step point": 28057,
    "Intermediate step point": "-",
    "Top step point": 30390,
    "Years until pay progression": 3,
    "Difference in entry pay": -3568,
    "Difference after 2 years": -3568,
    "Difference after 3 years": -5901,
    "Difference after 5 years": -5901
  },
  "Colindale_EO": {
    "Workplace": "Colindale",
    "Geography": "Inner",
    "Grade": "EO",
    "Minimum": 27690,
    "Maximum": 32203,
    "AfC region": "Colindale - High Cost Area Supplement (outer)",
    "AfC band": "Band 5",
    "Entry step point": 31163,
    "Intermediate step point": 33557,
    "Top step point": 37875,
    "Years until pay progression": 2,
    "Difference in entry pay": -3473,
    "Difference after 2 years": -5867,
    "Difference after 3 years": -5867,
    "Difference after 5 years": -10185
  },
  "Colindale_HEO": {
    "Workplace": "Colindale",
    "Geography": "Inner",
    "Grade": "HEO",
    "Minimum": 32978,
    "Maximum": 39691,
    "AfC region": "Colindale - High Cost Area Supplement (outer)",
    "AfC band": "Band 6",
    "Entry step point": 38762,
    "Intermediate step point": 40749,
    "Top step point": 45765,
    "Years until pay progression": "2 then 3",
    "Difference in entry pay": -5784,
    "Difference after 2 years": -7771,
    "Difference after 3 years": -7771,
    "Difference after 5 years": -12787
  },
  "Colindale_SEO": {
    "Workplace": "Colindale",
    "Geography": "Inner",
    "Grade": "SEO",
    "Minimum": 40876,
    "Maximum": 45998,
    "AfC region": "Colindale - High Cost Area Supplement (outer)",
    "AfC band": "Band 7",
    "Entry step point": 46836,
    "Intermediate step point": 48983,
    "Top step point": 52849,
    "Years until pay progression": "2 then 3",
    "Difference in entry pay": -5960,
    "Difference after 2 years": -8107,
    "Difference after 3 years": -8107,
    "Difference after 5 years": -11973
  },
  "Colindale_Grade 7": {
    "Workplace": "Colindale",
    "Geography": "Inner",
    "Grade": "Grade 7",
    "Minimum": 53396,
    "Maximum": 62286,
    "AfC region": "Colindale - High Cost Area Supplement (outer)",
    "AfC band": "Band 8a ",
    "Entry step point": 53703,
    "Intermediate step point": "-",
    "Top step point": 59796,
    "Years until pay progression": 5,
    "Difference in entry pay": -307,
    "Difference after 2 years": -307,
    "Difference after 3 years": -6400,
    "Difference after 5 years": -6400
  },
  "Colindale_Grade 7 (upper)": {
    "Workplace": "Colindale",
    "Geography": "Inner",
    "Grade": "Grade 7 (upper)",
    "Minimum": 60574,
    "Maximum": 62286,
    "AfC region": "Colindale - High Cost Area Supplement (outer)",
    "AfC band": "Band 8b",
    "Entry step point": 61341,
    "Intermediate step point": "-",
    "Top step point": 70439,
    "Years until pay progression": 5,
    "Difference in entry pay": -767,
    "Difference after 2 years": -767,
    "Difference after 3 years": -9865,
    "Difference after 5 years": -9865
  },
  "Colindale_Grade 6": {
    "Workplace": "Colindale",
    "Geography": "Inner",
    "Grade": "Grade 6",
    "Minimum": 66291,
    "Maximum": 75411,
    "AfC region": "Colindale - High Cost Area Supplement (outer)",
    "AfC band": "Band 8c",
    "Entry step point": 72241,
    "Intermediate step point": "-",
    "Top step point": 82451,
    "Years until pay progression": 5,
    "Difference in entry pay": -5950,
    "Difference after 2 years": -5950,
    "Difference after 3 years": -16160,
    "Difference after 5 years": -16160
  },
  "Harlow_AA": {
    "Workplace": "Harlow",
    "Geography": "Outer",
    "Grade": "AA",
    "Minimum": 21082,
    "Maximum": 21082,
    "AfC region": "High Cost Area Supplement (fringe)",
    "AfC band": "Band 3",
    "Entry step point": 22866,
    "Intermediate step point": "-",
    "Top step point": 24336,
    "Years until pay progression": 2,
    "Difference in entry pay": -1784,
    "Difference after 2 years": -3254,
    "Difference after 3 years": -3254,
    "Difference after 5 years": -3254
  },
  "Harlow_AO": {
    "Workplace": "Harlow",
    "Geography": "Outer",
    "Grade": "AO",
    "Minimum": 22479,
    "Maximum": 23456,
    "AfC region": "High Cost Area Supplement (fringe)",
    "AfC band": "Band 4",
    "Entry step point": 25147,
    "Intermediate step point": "-",
    "Top step point": 27597,
    "Years until pay progression": 3,
    "Difference in entry pay": -2668,
    "Difference after 2 years": -2668,
    "Difference after 3 years": -5118,
    "Difference after 5 years": -5118
  },
  "Harlow_EO": {
    "Workplace": "Harlow",
    "Geography": "Outer",
    "Grade": "EO",
    "Minimum": 25762,
    "Maximum": 30339,
    "AfC region": "High Cost Area Supplement (fringe)",
    "AfC band": "Band 5",
    "Entry step point": 28408,
    "Intermediate step point": 30639,
    "Top step point": 34581,
    "Years until pay progression": 2,
    "Difference in entry pay": -2646,
    "Difference after 2 years": -4877,
    "Difference after 3 years": -4877,
    "Difference after 5 years": -8819
  },
  "Harlow_HEO": {
    "Workplace": "Harlow",
    "Geography": "Outer",
    "Grade": "HEO",
    "Minimum": 31070,
    "Maximum": 37829,
    "AfC region": "High Cost Area Supplement (fringe)",
    "AfC band": "Band 6",
    "Entry step point": 35392,
    "Intermediate step point": 37351,
    "Top step point": 42503,
    "Years until pay progression": "2 then 3",
    "Difference in entry pay": -4322,
    "Difference after 2 years": -6281,
    "Difference after 3 years": -6281,
    "Difference after 5 years": -11433
  },
  "Harlow_SEO": {
    "Workplace": "Harlow",
    "Geography": "Outer",
    "Grade": "SEO",
    "Minimum": 38967,
    "Maximum": 44240,
    "AfC region": "High Cost Area Supplement (fringe)",
    "AfC band": "Band 7",
    "Entry step point": 43574,
    "Intermediate step point": 45721,
    "Top step point": 49587,
    "Years until pay progression": "2 then 3",
    "Difference in entry pay": -4607,
    "Difference after 2 years": -6754,
    "Difference after 3 years": -6754,
    "Difference after 5 years": -10620
  },
  "Harlow_Grade 7": {
    "Workplace": "Harlow",
    "Geography": "Outer",
    "Grade": "Grade 7",
    "Minimum": 51494,
    "Maximum": 60528,
    "AfC region": "High Cost Area Supplement (fringe)",
    "AfC band": "Band 8a ",
    "Entry step point": 50441,
    "Intermediate step point": "-",
    "Top step point": 56534,
    "Years until pay progression": 5,
    "Difference in entry pay": 1053,
    "Difference after 2 years": 1053,
    "Difference after 3 years": -5040,
    "Difference after 5 years": -5040
  },
  "Harlow_Grade 7 (upper)": {
    "Workplace": "Harlow",
    "Geography": "Outer",
    "Grade": "Grade 7 (upper)",
    "Minimum": 58694,
    "Maximum": 60528,
    "AfC region": "High Cost Area Supplement (fringe)",
    "AfC band": "Band 8b",
    "Entry step point": 58079,
    "Intermediate step point": "-",
    "Top step point": 67177,
    "Years until pay progression": 5,
    "Difference in entry pay": 615,
    "Difference after 2 years": 615,
    "Difference after 3 years": -8483,
    "Difference after 5 years": -8483
  },
  "Harlow_Grade 6": {
    "Workplace": "Harlow",
    "Geography": "Outer",
    "Grade": "Grade 6",
    "Minimum": 64390,
    "Maximum": 73652,
    "AfC region": "High Cost Area Supplement (fringe)",
    "AfC band": "Band 8c",
    "Entry step point": 68979,
    "Intermediate step point": "-",
    "Top step point": 79189,
    "Years until pay progression": 5,
    "Difference in entry pay": -4589,
    "Difference after 2 years": -4589,
    "Difference after 3 years": -14799,
    "Difference after 5 years": -14799
  },
  "Outside Greater London_AA": {
    "Workplace": "Outside Greater London",
    "Geography": "National",
    "Grade": "AA",
    "Minimum": 20103,
    "Maximum": 20103,
    "AfC region": "National ",
    "AfC band": "Band 3",
    "Entry step point": 21730,
    "Intermediate step point": "-",
    "Top step point": 23177,
    "Years until pay progression": 2,
    "Difference in entry pay": -1627,
    "Difference after 2 years": -3074,
    "Difference after 3 years": -3074,
    "Difference after 5 years": -3074
  },
  "Outside Greater London_AO": {
    "Workplace": "Outside Greater London",
    "Geography": "National",
    "Grade": "AO",
    "Minimum": 20472,
    "Maximum": 22377,
    "AfC region": "National ",
    "AfC band": "Band 4",
    "Entry step point": 23949,
    "Intermediate step point": "-",
    "Top step point": 26282,
    "Years until pay progression": 3,
    "Difference in entry pay": -3477,
    "Difference after 2 years": -3477,
    "Difference after 3 years": -5810,
    "Difference after 5 years": -5810
  },
  "Outside Greater London_EO": {
    "Workplace": "Outside Greater London",
    "Geography": "National",
    "Grade": "EO",
    "Minimum": 24091,
    "Maximum": 28195,
    "AfC region": "National ",
    "AfC band": "Band 5",
    "Entry step point": 27055,
    "Intermediate step point": 29180,
    "Top step point": 32934,
    "Years until pay progression": 2,
    "Difference in entry pay": -2964,
    "Difference after 2 years": -5089,
    "Difference after 3 years": -5089,
    "Difference after 5 years": -8843
  },
  "Outside Greater London_HEO": {
    "Workplace": "Outside Greater London",
    "Geography": "National",
    "Grade": "HEO",
    "Minimum": 29160,
    "Maximum": 35612,
    "AfC region": "National ",
    "AfC band": "Band 6",
    "Entry step point": 33706,
    "Intermediate step point": 35572,
    "Top step point": 40588,
    "Years until pay progression": "2 then 3",
    "Difference in entry pay": -4546,
    "Difference after 2 years": -6412,
    "Difference after 3 years": -6412,
    "Difference after 5 years": -11428
  },
  "Outside Greater London_SEO": {
    "Workplace": "Outside Greater London",
    "Geography": "National",
    "Grade": "SEO",
    "Minimum": 37056,
    "Maximum": 42481,
    "AfC region": "National ",
    "AfC band": "Band 7",
    "Entry step point": 41659,
    "Intermediate step point": 43806,
    "Top step point": 47672,
    "Years until pay progression": "2 then 3",
    "Difference in entry pay": -4603,
    "Difference after 2 years": -6750,
    "Difference after 3 years": -6750,
    "Difference after 5 years": -10616
  },
  "Outside Greater London_Grade 7": {
    "Workplace": "Outside Greater London",
    "Geography": "National",
    "Grade": "Grade 7",
    "Minimum": 49592,
    "Maximum": 58769,
    "AfC region": "National ",
    "AfC band": "Band 8a ",
    "Entry step point": 48526,
    "Intermediate step point": "-",
    "Top step point": 54619,
    "Years until pay progression": 5,
    "Difference in entry pay": 1066,
    "Difference after 2 years": 1066,
    "Difference after 3 years": -5027,
    "Difference after 5 years": -5027
  },
  "Outside Greater London_Grade 7 (upper)": {
    "Workplace": "Outside Greater London",
    "Geography": "National",
    "Grade": "Grade 7 (upper)",
    "Minimum": 56770,
    "Maximum": 58769,
    "AfC region": "National ",
    "AfC band": "Band 8b",
    "Entry step point": 56164,
    "Intermediate step point": "-",
    "Top step point": 65262,
    "Years until pay progression": 5,
    "Difference in entry pay": 606,
    "Difference after 2 years": 606,
    "Difference after 3 years": -8492,
    "Difference after 5 years": -8492
  },
  "Outside Greater London_Grade 6": {
    "Workplace": "Outside Greater London",
    "Geography": "National",
    "Grade": "Grade 6",
    "Minimum": 62489,
    "Maximum": 71893,
    "AfC region": "National ",
    "AfC band": "Band 8c",
    "Entry step point": 67064,
    "Intermediate step point": "-",
    "Top step point": 77274,
    "Years until pay progression": 5,
    "Difference in entry pay": -4575,
    "Difference after 2 years": -4575,
    "Difference after 3 years": -14785,
    "Difference after 5 years": -14785
  },
  "Nobel House/Canary Wharf_AA": {
    "Workplace": "Nobel House/Canary Wharf",
    "Geography": "Inner",
    "Grade": "AA",
    "Minimum": 23469,
    "Maximum": 23469,
    "AfC region": "Central London - High Cost Area Supplement (inner)",
    "AfC band": "Band 3",
    "Entry step point": 26618,
    "Intermediate step point": "-",
    "Top step point": 28065,
    "Years until pay progression": 2,
    "Difference in entry pay": -3149,
    "Difference after 2 years": -4596,
    "Difference after 3 years": -4596,
    "Difference after 5 years": -4596
  },
  "Nobel House/Canary Wharf_AO": {
    "Workplace": "Nobel House/Canary Wharf",
    "Geography": "Inner",
    "Grade": "AO",
    "Minimum": 24489,
    "Maximum": 25066,
    "AfC region": "Central London - High Cost Area Supplement (inner)",
    "AfC band": "Band 4",
    "Entry step point": 28837,
    "Intermediate step point": "-",
    "Top step point": 31539,
    "Years until pay progression": 3,
    "Difference in entry pay": -4348,
    "Difference after 2 years": -4348,
    "Difference after 3 years": -7050,
    "Difference after 5 years": -7050
  },
  "Nobel House/Canary Wharf_EO": {
    "Workplace": "Nobel House/Canary Wharf",
    "Geography": "Inner",
    "Grade": "EO",
    "Minimum": 27690,
    "Maximum": 32203,
    "AfC region": "Central London - High Cost Area Supplement (inner)",
    "AfC band": "Band 5",
    "Entry step point": 32466,
    "Intermediate step point": 35016,
    "Top step point": 39521,
    "Years until pay progression": 2,
    "Difference in entry pay": -4776,
    "Difference after 2 years": -7326,
    "Difference after 3 years": -7326,
    "Difference after 5 years": -11831
  },
  "Nobel House/Canary Wharf_HEO": {
    "Workplace": "Nobel House/Canary Wharf",
    "Geography": "Inner",
    "Grade": "HEO",
    "Minimum": 32978,
    "Maximum": 39691,
    "AfC region": "Central London - High Cost Area Supplement (inner)",
    "AfC band": "Band 6",
    "Entry step point": 40448,
    "Intermediate step point": 42687,
    "Top step point": 47965,
    "Years until pay progression": "2 then 3",
    "Difference in entry pay": -7470,
    "Difference after 2 years": -9709,
    "Difference after 3 years": -9709,
    "Difference after 5 years": -14987
  },
  "Nobel House/Canary Wharf_SEO": {
    "Workplace": "Nobel House/Canary Wharf",
    "Geography": "Inner",
    "Grade": "SEO",
    "Minimum": 40876,
    "Maximum": 45998,
    "AfC region": "Central London - High Cost Area Supplement (inner)",
    "AfC band": "Band 7",
    "Entry step point": 49036,
    "Intermediate step point": 51183,
    "Top step point": 55049,
    "Years until pay progression": "2 then 3",
    "Difference in entry pay": -8160,
    "Difference after 2 years": -10307,
    "Difference after 3 years": -10307,
    "Difference after 5 years": -14173
  },
  "Nobel House/Canary Wharf_Grade 7": {
    "Workplace": "Nobel House/Canary Wharf",
    "Geography": "Inner",
    "Grade": "Grade 7",
    "Minimum": 53396,
    "Maximum": 62286,
    "AfC region": "Central London - High Cost Area Supplement (inner)",
    "AfC band": "Band 8a ",
    "Entry step point": 55903,
    "Intermediate step point": "-",
    "Top step point": 61996,
    "Years until pay progression": 5,
    "Difference in entry pay": -2507,
    "Difference after 2 years": -2507,
    "Difference after 3 years": -8600,
    "Difference after 5 years": -8600
  },
  "Nobel House/Canary Wharf_Grade 7 (upper)": {
    "Workplace": "Nobel House/Canary Wharf",
    "Geography": "Inner",
    "Grade": "Grade 7 (upper)",
    "Minimum": 60574,
    "Maximum": 62286,
    "AfC region": "Central London - High Cost Area Supplement (inner)",
    "AfC band": "Band 8b",
    "Entry step point": 63541,
    "Intermediate step point": "-",
    "Top step point": 72639,
    "Years until pay progression": 5,
    "Difference in entry pay": -2967,
    "Difference after 2 years": -2967,
    "Difference after 3 years": -12065,
    "Difference after 5 years": -12065
  },
  "Nobel House/Canary Wharf_Grade 6": {
    "Workplace": "Nobel House/Canary Wharf",
    "Geography": "Inner",
    "Grade": "Grade 6",
    "Minimum": 66291,
    "Maximum": 75411,
    "AfC region": "Central London - High Cost Area Supplement (inner)",
    "AfC band": "Band 8c",
    "Entry step point": 74441,
    "Intermediate step point": "-",
    "Top step point": 84651,
    "Years until pay progression": 5,
    "Difference in entry pay": -8150,
    "Difference after 2 years": -8150,
    "Difference after 3 years": -18360,
    "Difference after 5 years": -18360
  }
}
